
GET http://localhost:3000/api/todos/
//Fetches all 

###

POST http://localhost:3000/api/todos/
Content-Type: application/json

{   "id": 4,
    "name": "Tandläkare",
    "place": "Göteborg",
    "time": "16:00"    
}
//Adds a new post

###

PUT http://localhost:3000/api/todos/3/
Content-Type: application/application/json

  {
   
      "name": "Tandläkare",
      "place": "Göteborg",
      "time": "17:00",
    };

//Updates a specific index


// Uppdaterar idnummret till en sträng.. i id 3 " fika" , varför?

###

DELETE  http://localhost:3000/api/todos/3
//Removes a specific index.

