
GET http://localhost:3000/api/todo

//Fetches all 

###


POST http://localhost:3000/api/todo/
Content-Type: application/json

{   "id": 4,
    "name": "Tandläkare",
    "place": "Göteborg",
    "time": "16:00"
   
   
    
}
//Adds a new post

###

PUT http://localhost:3000/api/todo/id/4
Content-Type: application/json

{   "id": 4,
    "name": "Tandläkare",
     "place": "Göteborg",
    "time": "17:00"
  
    
}
//Updates the last one

###

DELETE  http://localhost:3000/api/todo/id/

//Removes the last one

